# Generated by Django 5.2.9 on 2026-01-28 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='total_marks',
        ),
    ]
